<a href="https://colab.research.google.com/github/Data4i/Advanced_Compute_Vision/blob/main/torch_examples_2_continuation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np
import time

In [3]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [4]:
# Testing Out time ranges of tensor with GPU and pure numpy

tensor_1 = torch.randint(low = 2, high = 50, size = (4,3), device = device).to(dtype = torch.float)
tensor_2 = torch.randint(low = 2, high = 50, size = (3,4), device = device).to(dtype = torch.float)

tensor_start_time = time.time()
multiplied_tensor = tensor_1 @ tensor_2
tensor_end_time = time.time()

numpy_array_1 = np.random.randint(low = 2, high = 50, size = (4,3))
numpy_array_2 = np.random.randint(low = 2, high = 50, size = (4,3))

numpy_start_time = time.time()
multiplied_numpy_array = np.multiply(numpy_array_1, numpy_array_2)
numpy_end_time = time.time()

print(f'Time taken for the GPU Tensor operation to execute: {tensor_end_time - tensor_start_time}')
print(f'Time taken for the numpy operation run on cpu to execute: {numpy_end_time - numpy_start_time}')

Time taken for the GPU Tensor operation to execute: 0.1194608211517334
Time taken for the numpy operation run on cpu to execute: 5.7220458984375e-05


In [5]:
probabilities = torch.tensor([0.3, 0.7])
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 0, 1, 0, 0, 1, 1, 1, 1, 1])


In [6]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [7]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [8]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [9]:
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.tril(torch.ones(5,5)) == 0

tensor([[False,  True,  True,  True,  True],
        [False, False,  True,  True,  True],
        [False, False, False,  True,  True],
        [False, False, False, False,  True],
        [False, False, False, False, False]])

In [11]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [12]:
input = torch.zeros(2,3,4)
print(f'input: {input}, input_shape: {input.shape}')
out = input.transpose(0,2)
print(f'Output: {out}, Output_shape: {out.shape}')

input: tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]), input_shape: torch.Size([2, 3, 4])
Output: tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]), Output_shape: torch.Size([4, 3, 2])


In [13]:
# Stacking Tensors
tensor_1 = torch.tensor([1,2,3])
tensor_2 = torch.tensor([4,5,6])
tensor_3 = torch.tensor([7,8,9])

stacked_tensors = torch.stack([tensor_1, tensor_2, tensor_3])
stacked_tensors

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
from torch import nn
sample = torch.tensor([10, 10, 10], dtype = torch.float)
linear = nn.Linear(3,3, bias = False)
print(linear(sample))

tensor([-8.4705,  5.8138,  1.2341], grad_fn=<SqueezeBackward4>)


In [15]:
import torch.nn.functional as F

# Create a tensor
tensor_1 = torch.tensor([1., 2., 3.])

softmax_output = F.softmax(tensor_1, dim = 0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [16]:
# Define vocabulary size and embedding dimension
vocab_size = 10
embedding_dim = 5

# Create an embedding layer
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Input tensor containing indices to be embedded
input_indices = torch.tensor([1, 4, 6, 2])

# Apply the embedding layer to get dense representations
embedded_vectors = embedding_layer(input_indices)

print(embedded_vectors)
print(embedded_vectors.shape)


tensor([[-0.5108,  0.8445,  0.8489,  0.3742,  1.5506],
        [ 0.3705,  0.0929, -0.8843, -1.1747,  0.6020],
        [ 0.2028, -0.0392,  0.6936,  1.3527,  0.2366],
        [-0.3608, -0.4992,  0.3038, -0.1391, -0.6288]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([4, 5])


In [21]:
torch.rand((3,2))

tensor([[0.7707, 0.1101],
        [0.0601, 0.8665],
        [0.9685, 0.2284]])